// flow-typed signature: 530047d4ba6f368a291f27e79d5dbddd
// flow-typed version: <<STUB>>/babel-plugin-transform-require-ignore_v^0.0.2/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-require-ignore'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-require-ignore' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-require-ignore/lib/__tests__/helpers/babelEql' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-require-ignore/lib/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-require-ignore/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-require-ignore/lib/__tests__/helpers/babelEql.js' {
  declare module.exports: $Exports<'babel-plugin-transform-require-ignore/lib/__tests__/helpers/babelEql'>;
}
declare module 'babel-plugin-transform-require-ignore/lib/__tests__/index.spec.js' {
  declare module.exports: $Exports<'babel-plugin-transform-require-ignore/lib/__tests__/index.spec'>;
}
declare module 'babel-plugin-transform-require-ignore/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-require-ignore/lib/index'>;
}
