// flow-typed signature: 468754cf0af5ba9a3ff7a2164bb89293
// flow-typed version: <<STUB>>/expose_v^0.1.4/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expose'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expose' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expose/lib/expose' {
  declare module.exports: any;
}

declare module 'expose/test/defaults/lib/a' {
  declare module.exports: any;
}

declare module 'expose/test/defaults/lib/b' {
  declare module.exports: any;
}

declare module 'expose/test/defaults/lib/inc/c' {
  declare module.exports: any;
}

declare module 'expose/test/defaults/lib/node_modules/d' {
  declare module.exports: any;
}

declare module 'expose/test/defaults/test' {
  declare module.exports: any;
}

declare module 'expose/test/nondefault/src/a' {
  declare module.exports: any;
}

declare module 'expose/test/nondefault/test' {
  declare module.exports: any;
}

declare module 'expose/test/nonobj/lib/array' {
  declare module.exports: any;
}

declare module 'expose/test/nonobj/lib/string' {
  declare module.exports: any;
}

declare module 'expose/test/nonobj/test' {
  declare module.exports: any;
}

declare module 'expose/test/submod/node_modules/lib/a' {
  declare module.exports: any;
}

declare module 'expose/test/submod/node_modules/lib/b' {
  declare module.exports: any;
}

declare module 'expose/test/submod/node_modules/node_modules/c' {
  declare module.exports: any;
}

declare module 'expose/test/submod/node_modules/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expose/index' {
  declare module.exports: $Exports<'expose'>;
}
declare module 'expose/index.js' {
  declare module.exports: $Exports<'expose'>;
}
declare module 'expose/lib/expose.js' {
  declare module.exports: $Exports<'expose/lib/expose'>;
}
declare module 'expose/test/defaults/lib/a.js' {
  declare module.exports: $Exports<'expose/test/defaults/lib/a'>;
}
declare module 'expose/test/defaults/lib/b.js' {
  declare module.exports: $Exports<'expose/test/defaults/lib/b'>;
}
declare module 'expose/test/defaults/lib/inc/c.js' {
  declare module.exports: $Exports<'expose/test/defaults/lib/inc/c'>;
}
declare module 'expose/test/defaults/lib/node_modules/d.js' {
  declare module.exports: $Exports<'expose/test/defaults/lib/node_modules/d'>;
}
declare module 'expose/test/defaults/test.js' {
  declare module.exports: $Exports<'expose/test/defaults/test'>;
}
declare module 'expose/test/nondefault/src/a.js' {
  declare module.exports: $Exports<'expose/test/nondefault/src/a'>;
}
declare module 'expose/test/nondefault/test.js' {
  declare module.exports: $Exports<'expose/test/nondefault/test'>;
}
declare module 'expose/test/nonobj/lib/array.js' {
  declare module.exports: $Exports<'expose/test/nonobj/lib/array'>;
}
declare module 'expose/test/nonobj/lib/string.js' {
  declare module.exports: $Exports<'expose/test/nonobj/lib/string'>;
}
declare module 'expose/test/nonobj/test.js' {
  declare module.exports: $Exports<'expose/test/nonobj/test'>;
}
declare module 'expose/test/submod/node_modules/lib/a.js' {
  declare module.exports: $Exports<'expose/test/submod/node_modules/lib/a'>;
}
declare module 'expose/test/submod/node_modules/lib/b.js' {
  declare module.exports: $Exports<'expose/test/submod/node_modules/lib/b'>;
}
declare module 'expose/test/submod/node_modules/node_modules/c.js' {
  declare module.exports: $Exports<'expose/test/submod/node_modules/node_modules/c'>;
}
declare module 'expose/test/submod/node_modules/test.js' {
  declare module.exports: $Exports<'expose/test/submod/node_modules/test'>;
}
