// flow-typed signature: 5ac0f2ff21c80fdb6239b6c9bb0a1e9d
// flow-typed version: <<STUB>>/ip_v^1.1.5/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ip/lib/ip' {
  declare module.exports: any;
}

declare module 'ip/test/api-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ip/lib/ip.js' {
  declare module.exports: $Exports<'ip/lib/ip'>;
}
declare module 'ip/test/api-test.js' {
  declare module.exports: $Exports<'ip/test/api-test'>;
}
