// flow-typed signature: 87099ea0a46ef46b6a932dd02cea2180
// flow-typed version: <<STUB>>/koa-body_v^2.0.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-body'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-body' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-body/index' {
  declare module.exports: $Exports<'koa-body'>;
}
declare module 'koa-body/index.js' {
  declare module.exports: $Exports<'koa-body'>;
}
