// flow-typed signature: dc08f9b295362308a40adf61114f9936
// flow-typed version: <<STUB>>/twitter_v^1.7.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'twitter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'twitter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'twitter/lib/parser' {
  declare module.exports: any;
}

declare module 'twitter/lib/twitter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'twitter/lib/parser.js' {
  declare module.exports: $Exports<'twitter/lib/parser'>;
}
declare module 'twitter/lib/twitter.js' {
  declare module.exports: $Exports<'twitter/lib/twitter'>;
}
