// flow-typed signature: 4bb1ef861e643e1027e7e56ea2a3a2b3
// flow-typed version: <<STUB>>/urllib_v^2.22.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'urllib'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'urllib' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'urllib/lib/httpclient' {
  declare module.exports: any;
}

declare module 'urllib/lib/httpclient2' {
  declare module.exports: any;
}

declare module 'urllib/lib/index' {
  declare module.exports: any;
}

declare module 'urllib/lib/urllib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'urllib/lib/httpclient.js' {
  declare module.exports: $Exports<'urllib/lib/httpclient'>;
}
declare module 'urllib/lib/httpclient2.js' {
  declare module.exports: $Exports<'urllib/lib/httpclient2'>;
}
declare module 'urllib/lib/index.js' {
  declare module.exports: $Exports<'urllib/lib/index'>;
}
declare module 'urllib/lib/urllib.js' {
  declare module.exports: $Exports<'urllib/lib/urllib'>;
}
