// flow-typed signature: 1a942367eab772253f95d0fd5458a2aa
// flow-typed version: <<STUB>>/vue-ssr-webpack-plugin_v^3.0.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-ssr-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-ssr-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-ssr-webpack-plugin/lib/client' {
  declare module.exports: any;
}

declare module 'vue-ssr-webpack-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'vue-ssr-webpack-plugin/lib/server' {
  declare module.exports: any;
}

declare module 'vue-ssr-webpack-plugin/lib/util' {
  declare module.exports: any;
}

declare module 'vue-ssr-webpack-plugin/lib/validate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-ssr-webpack-plugin/lib/client.js' {
  declare module.exports: $Exports<'vue-ssr-webpack-plugin/lib/client'>;
}
declare module 'vue-ssr-webpack-plugin/lib/index.js' {
  declare module.exports: $Exports<'vue-ssr-webpack-plugin/lib/index'>;
}
declare module 'vue-ssr-webpack-plugin/lib/server.js' {
  declare module.exports: $Exports<'vue-ssr-webpack-plugin/lib/server'>;
}
declare module 'vue-ssr-webpack-plugin/lib/util.js' {
  declare module.exports: $Exports<'vue-ssr-webpack-plugin/lib/util'>;
}
declare module 'vue-ssr-webpack-plugin/lib/validate.js' {
  declare module.exports: $Exports<'vue-ssr-webpack-plugin/lib/validate'>;
}
