// flow-typed signature: 68b8a22581874304a205c2a255417f57
// flow-typed version: <<STUB>>/vue-upload-component_v^2.3.0-beta.2/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-upload-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-upload-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-upload-component/dist/example' {
  declare module.exports: any;
}

declare module 'vue-upload-component/dist/vue-upload-component' {
  declare module.exports: any;
}

declare module 'vue-upload-component/dist/vue-upload-component.min' {
  declare module.exports: any;
}

declare module 'vue-upload-component/example/index' {
  declare module.exports: any;
}

declare module 'vue-upload-component/example/store' {
  declare module.exports: any;
}

declare module 'vue-upload-component/src/index' {
  declare module.exports: any;
}

declare module 'vue-upload-component/webpack.config.build' {
  declare module.exports: any;
}

declare module 'vue-upload-component/webpack.config.build.min' {
  declare module.exports: any;
}

declare module 'vue-upload-component/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-upload-component/dist/example.js' {
  declare module.exports: $Exports<'vue-upload-component/dist/example'>;
}
declare module 'vue-upload-component/dist/vue-upload-component.js' {
  declare module.exports: $Exports<'vue-upload-component/dist/vue-upload-component'>;
}
declare module 'vue-upload-component/dist/vue-upload-component.min.js' {
  declare module.exports: $Exports<'vue-upload-component/dist/vue-upload-component.min'>;
}
declare module 'vue-upload-component/example/index.js' {
  declare module.exports: $Exports<'vue-upload-component/example/index'>;
}
declare module 'vue-upload-component/example/store.js' {
  declare module.exports: $Exports<'vue-upload-component/example/store'>;
}
declare module 'vue-upload-component/src/index.js' {
  declare module.exports: $Exports<'vue-upload-component/src/index'>;
}
declare module 'vue-upload-component/webpack.config.build.js' {
  declare module.exports: $Exports<'vue-upload-component/webpack.config.build'>;
}
declare module 'vue-upload-component/webpack.config.build.min.js' {
  declare module.exports: $Exports<'vue-upload-component/webpack.config.build.min'>;
}
declare module 'vue-upload-component/webpack.config.js' {
  declare module.exports: $Exports<'vue-upload-component/webpack.config'>;
}
